/**
 * generated by Xtext 2.12.0
 */
package org.standardhealh.cimpl.dsl.cimpl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subsets</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.standardhealh.cimpl.dsl.cimpl.Subsets#getName <em>Name</em>}</li>
 *   <li>{@link org.standardhealh.cimpl.dsl.cimpl.Subsets#getSubsets <em>Subsets</em>}</li>
 * </ul>
 *
 * @see org.standardhealh.cimpl.dsl.cimpl.CimplPackage#getSubsets()
 * @model
 * @generated
 */
public interface Subsets extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.standardhealh.cimpl.dsl.cimpl.CimplPackage#getSubsets_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.standardhealh.cimpl.dsl.cimpl.Subsets#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Subsets</b></em>' containment reference list.
   * The list contents are of type {@link org.standardhealh.cimpl.dsl.cimpl.Subset}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Subsets</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subsets</em>' containment reference list.
   * @see org.standardhealh.cimpl.dsl.cimpl.CimplPackage#getSubsets_Subsets()
   * @model containment="true"
   * @generated
   */
  EList<Subset> getSubsets();

} // Subsets
