/**
 * generated by Xtext 2.12.0
 */
package org.standardhealh.cimpl.dsl.cimpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.standardhealh.cimpl.dsl.cimpl.CimplPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
} // Value
