/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi;

import gov.us.fhim.xtext.cimi.AbstractCIMIDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CIMIDSLRuntimeModule extends AbstractCIMIDSLRuntimeModule {
}
