/*
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CIMIDSLStandaloneSetup extends CIMIDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new CIMIDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
