/*
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CIMIDSLRuntimeModule extends AbstractCIMIDSLRuntimeModule {
}
