/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage
 * @generated
 */
public interface CIMIDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CIMIDSLFactory eINSTANCE = gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Archetype Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Archetype Model</em>'.
   * @generated
   */
  ArchetypeModel createArchetypeModel();

  /**
   * Returns a new object of class '<em>Archetype</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Archetype</em>'.
   * @generated
   */
  Archetype createArchetype();

  /**
   * Returns a new object of class '<em>Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description</em>'.
   * @generated
   */
  Description createDescription();

  /**
   * Returns a new object of class '<em>Details</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Details</em>'.
   * @generated
   */
  Details createDetails();

  /**
   * Returns a new object of class '<em>Other Details</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other Details</em>'.
   * @generated
   */
  OtherDetails createOtherDetails();

  /**
   * Returns a new object of class '<em>Original Author</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Original Author</em>'.
   * @generated
   */
  OriginalAuthor createOriginalAuthor();

  /**
   * Returns a new object of class '<em>Languge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Languge</em>'.
   * @generated
   */
  Languge createLanguge();

  /**
   * Returns a new object of class '<em>Matches</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Matches</em>'.
   * @generated
   */
  Matches createMatches();

  /**
   * Returns a new object of class '<em>Terminology</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminology</em>'.
   * @generated
   */
  Terminology createTerminology();

  /**
   * Returns a new object of class '<em>Term Definitions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term Definitions</em>'.
   * @generated
   */
  TermDefinitions createTermDefinitions();

  /**
   * Returns a new object of class '<em>Term Bindings</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term Bindings</em>'.
   * @generated
   */
  TermBindings createTermBindings();

  /**
   * Returns a new object of class '<em>Term Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term Definition</em>'.
   * @generated
   */
  TermDefinition createTermDefinition();

  /**
   * Returns a new object of class '<em>Term Binding</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term Binding</em>'.
   * @generated
   */
  TermBinding createTermBinding();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CIMIDSLPackage getCIMIDSLPackage();

} //CIMIDSLFactory
