/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLFactory
 * @model kind="package"
 * @generated
 */
public interface CIMIDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cIMIDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.us.gov/fhim/xtext/cimi/CIMIDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cIMIDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CIMIDSLPackage eINSTANCE = gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeModelImpl <em>Archetype Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeModelImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getArchetypeModel()
   * @generated
   */
  int ARCHETYPE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Archetype Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeImpl <em>Archetype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getArchetype()
   * @generated
   */
  int ARCHETYPE = 1;

  /**
   * The feature id for the '<em><b>Adl version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__ADL_VERSION = 0;

  /**
   * The feature id for the '<em><b>Rm release</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__RM_RELEASE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__NAME = 2;

  /**
   * The feature id for the '<em><b>Language</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__LANGUAGE = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Terminology</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE__TERMINOLOGY = 6;

  /**
   * The number of structural features of the '<em>Archetype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHETYPE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Original Author</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__ORIGINAL_AUTHOR = 0;

  /**
   * The feature id for the '<em><b>Details</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__DETAILS = 1;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DetailsImpl <em>Details</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.DetailsImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getDetails()
   * @generated
   */
  int DETAILS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS__NAME = 0;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS__LANGUAGE = 1;

  /**
   * The feature id for the '<em><b>Use</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS__USE = 2;

  /**
   * The feature id for the '<em><b>Copyright</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS__COPYRIGHT = 3;

  /**
   * The feature id for the '<em><b>Other details</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS__OTHER_DETAILS = 4;

  /**
   * The number of structural features of the '<em>Details</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETAILS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.OtherDetailsImpl <em>Other Details</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.OtherDetailsImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getOtherDetails()
   * @generated
   */
  int OTHER_DETAILS = 4;

  /**
   * The feature id for the '<em><b>Lifecycle state</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__LIFECYCLE_STATE = 0;

  /**
   * The feature id for the '<em><b>Custodian namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__CUSTODIAN_NAMESPACE = 1;

  /**
   * The feature id for the '<em><b>Custodian organization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__CUSTODIAN_ORGANIZATION = 2;

  /**
   * The feature id for the '<em><b>License</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__LICENSE = 3;

  /**
   * The feature id for the '<em><b>Ip acknowledgement loinc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__IP_ACKNOWLEDGEMENT_LOINC = 4;

  /**
   * The feature id for the '<em><b>Ip acknowledgement snomed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS__IP_ACKNOWLEDGEMENT_SNOMED = 5;

  /**
   * The number of structural features of the '<em>Other Details</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_DETAILS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.OriginalAuthorImpl <em>Original Author</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.OriginalAuthorImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getOriginalAuthor()
   * @generated
   */
  int ORIGINAL_AUTHOR = 5;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGINAL_AUTHOR__DATE = 0;

  /**
   * The feature id for the '<em><b>Organization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGINAL_AUTHOR__ORGANIZATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGINAL_AUTHOR__NAME = 2;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGINAL_AUTHOR__EMAIL = 3;

  /**
   * The number of structural features of the '<em>Original Author</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGINAL_AUTHOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.LangugeImpl <em>Languge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.LangugeImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getLanguge()
   * @generated
   */
  int LANGUGE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUGE__NAME = 0;

  /**
   * The number of structural features of the '<em>Languge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.MatchesImpl <em>Matches</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.MatchesImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getMatches()
   * @generated
   */
  int MATCHES = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES__NAME = 0;

  /**
   * The feature id for the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES__DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Submatch</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES__SUBMATCH = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES__VALUE = 3;

  /**
   * The feature id for the '<em><b>Value Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES__VALUE_DEFINITION = 4;

  /**
   * The number of structural features of the '<em>Matches</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCHES_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TerminologyImpl <em>Terminology</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TerminologyImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTerminology()
   * @generated
   */
  int TERMINOLOGY = 8;

  /**
   * The feature id for the '<em><b>Term Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINOLOGY__TERM_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Term Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINOLOGY__TERM_BINDING = 1;

  /**
   * The number of structural features of the '<em>Terminology</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINOLOGY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionsImpl <em>Term Definitions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionsImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermDefinitions()
   * @generated
   */
  int TERM_DEFINITIONS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITIONS__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Term Definitions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingsImpl <em>Term Bindings</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingsImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermBindings()
   * @generated
   */
  int TERM_BINDINGS = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDINGS__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDINGS__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Term Bindings</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDINGS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionImpl <em>Term Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermDefinition()
   * @generated
   */
  int TERM_DEFINITION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITION__TEXT = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITION__DESCRIPTION = 2;

  /**
   * The number of structural features of the '<em>Term Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingImpl <em>Term Binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingImpl
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermBinding()
   * @generated
   */
  int TERM_BINDING = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDING__NAME = 0;

  /**
   * The feature id for the '<em><b>Binding</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDING__BINDING = 1;

  /**
   * The number of structural features of the '<em>Term Binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_BINDING_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.ArchetypeModel <em>Archetype Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Archetype Model</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.ArchetypeModel
   * @generated
   */
  EClass getArchetypeModel();

  /**
   * Returns the meta object for the containment reference list '{@link gov.us.fhim.xtext.cimi.cIMIDSL.ArchetypeModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.ArchetypeModel#getElements()
   * @see #getArchetypeModel()
   * @generated
   */
  EReference getArchetypeModel_Elements();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype <em>Archetype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Archetype</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype
   * @generated
   */
  EClass getArchetype();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getAdl_version <em>Adl version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Adl version</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getAdl_version()
   * @see #getArchetype()
   * @generated
   */
  EAttribute getArchetype_Adl_version();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getRm_release <em>Rm release</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rm release</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getRm_release()
   * @see #getArchetype()
   * @generated
   */
  EAttribute getArchetype_Rm_release();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getName()
   * @see #getArchetype()
   * @generated
   */
  EAttribute getArchetype_Name();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Language</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getLanguage()
   * @see #getArchetype()
   * @generated
   */
  EReference getArchetype_Language();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getDescription()
   * @see #getArchetype()
   * @generated
   */
  EReference getArchetype_Description();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Definition</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getDefinition()
   * @see #getArchetype()
   * @generated
   */
  EReference getArchetype_Definition();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getTerminology <em>Terminology</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Terminology</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Archetype#getTerminology()
   * @see #getArchetype()
   * @generated
   */
  EReference getArchetype_Terminology();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getOriginalAuthor <em>Original Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Original Author</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Description#getOriginalAuthor()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_OriginalAuthor();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getDetails <em>Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Details</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Description#getDetails()
   * @see #getDescription()
   * @generated
   */
  EReference getDescription_Details();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details <em>Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Details</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details
   * @generated
   */
  EClass getDetails();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details#getName()
   * @see #getDetails()
   * @generated
   */
  EAttribute getDetails_Name();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Language</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details#getLanguage()
   * @see #getDetails()
   * @generated
   */
  EAttribute getDetails_Language();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getUse <em>Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Use</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details#getUse()
   * @see #getDetails()
   * @generated
   */
  EAttribute getDetails_Use();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getCopyright <em>Copyright</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Copyright</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details#getCopyright()
   * @see #getDetails()
   * @generated
   */
  EAttribute getDetails_Copyright();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getOther_details <em>Other details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Other details</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Details#getOther_details()
   * @see #getDetails()
   * @generated
   */
  EReference getDetails_Other_details();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails <em>Other Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Other Details</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails
   * @generated
   */
  EClass getOtherDetails();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getLifecycle_state <em>Lifecycle state</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lifecycle state</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getLifecycle_state()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_Lifecycle_state();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getCustodian_namespace <em>Custodian namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Custodian namespace</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getCustodian_namespace()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_Custodian_namespace();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getCustodian_organization <em>Custodian organization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Custodian organization</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getCustodian_organization()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_Custodian_organization();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getLicense <em>License</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>License</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getLicense()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_License();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getIp_acknowledgement_loinc <em>Ip acknowledgement loinc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip acknowledgement loinc</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getIp_acknowledgement_loinc()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_Ip_acknowledgement_loinc();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getIp_acknowledgement_snomed <em>Ip acknowledgement snomed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip acknowledgement snomed</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OtherDetails#getIp_acknowledgement_snomed()
   * @see #getOtherDetails()
   * @generated
   */
  EAttribute getOtherDetails_Ip_acknowledgement_snomed();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor <em>Original Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Original Author</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor
   * @generated
   */
  EClass getOriginalAuthor();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getDate()
   * @see #getOriginalAuthor()
   * @generated
   */
  EAttribute getOriginalAuthor_Date();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getOrganization <em>Organization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Organization</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getOrganization()
   * @see #getOriginalAuthor()
   * @generated
   */
  EAttribute getOriginalAuthor_Organization();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getName()
   * @see #getOriginalAuthor()
   * @generated
   */
  EAttribute getOriginalAuthor_Name();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor#getEmail()
   * @see #getOriginalAuthor()
   * @generated
   */
  EAttribute getOriginalAuthor_Email();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Languge <em>Languge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Languge</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Languge
   * @generated
   */
  EClass getLanguge();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Languge#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Languge#getName()
   * @see #getLanguge()
   * @generated
   */
  EAttribute getLanguge_Name();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches <em>Matches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Matches</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches
   * @generated
   */
  EClass getMatches();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getName()
   * @see #getMatches()
   * @generated
   */
  EAttribute getMatches_Name();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Definition</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getDefinition()
   * @see #getMatches()
   * @generated
   */
  EAttribute getMatches_Definition();

  /**
   * Returns the meta object for the containment reference list '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getSubmatch <em>Submatch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Submatch</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getSubmatch()
   * @see #getMatches()
   * @generated
   */
  EReference getMatches_Submatch();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getValue()
   * @see #getMatches()
   * @generated
   */
  EAttribute getMatches_Value();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getValueDefinition <em>Value Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value Definition</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Matches#getValueDefinition()
   * @see #getMatches()
   * @generated
   */
  EAttribute getMatches_ValueDefinition();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Terminology <em>Terminology</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminology</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Terminology
   * @generated
   */
  EClass getTerminology();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Terminology#getTermDefinition <em>Term Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term Definition</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Terminology#getTermDefinition()
   * @see #getTerminology()
   * @generated
   */
  EReference getTerminology_TermDefinition();

  /**
   * Returns the meta object for the containment reference '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Terminology#getTermBinding <em>Term Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term Binding</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.Terminology#getTermBinding()
   * @see #getTerminology()
   * @generated
   */
  EReference getTerminology_TermBinding();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions <em>Term Definitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term Definitions</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions
   * @generated
   */
  EClass getTermDefinitions();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getName()
   * @see #getTermDefinitions()
   * @generated
   */
  EAttribute getTermDefinitions_Name();

  /**
   * Returns the meta object for the containment reference list '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getElements()
   * @see #getTermDefinitions()
   * @generated
   */
  EReference getTermDefinitions_Elements();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings <em>Term Bindings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term Bindings</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings
   * @generated
   */
  EClass getTermBindings();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings#getName()
   * @see #getTermBindings()
   * @generated
   */
  EAttribute getTermBindings_Name();

  /**
   * Returns the meta object for the containment reference list '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBindings#getElements()
   * @see #getTermBindings()
   * @generated
   */
  EReference getTermBindings_Elements();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition <em>Term Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term Definition</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition
   * @generated
   */
  EClass getTermDefinition();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getName()
   * @see #getTermDefinition()
   * @generated
   */
  EAttribute getTermDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getText()
   * @see #getTermDefinition()
   * @generated
   */
  EAttribute getTermDefinition_Text();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition#getDescription()
   * @see #getTermDefinition()
   * @generated
   */
  EAttribute getTermDefinition_Description();

  /**
   * Returns the meta object for class '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding <em>Term Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term Binding</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding
   * @generated
   */
  EClass getTermBinding();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getName()
   * @see #getTermBinding()
   * @generated
   */
  EAttribute getTermBinding_Name();

  /**
   * Returns the meta object for the attribute '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getBinding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Binding</em>'.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getBinding()
   * @see #getTermBinding()
   * @generated
   */
  EAttribute getTermBinding_Binding();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CIMIDSLFactory getCIMIDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeModelImpl <em>Archetype Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeModelImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getArchetypeModel()
     * @generated
     */
    EClass ARCHETYPE_MODEL = eINSTANCE.getArchetypeModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHETYPE_MODEL__ELEMENTS = eINSTANCE.getArchetypeModel_Elements();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeImpl <em>Archetype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.ArchetypeImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getArchetype()
     * @generated
     */
    EClass ARCHETYPE = eINSTANCE.getArchetype();

    /**
     * The meta object literal for the '<em><b>Adl version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHETYPE__ADL_VERSION = eINSTANCE.getArchetype_Adl_version();

    /**
     * The meta object literal for the '<em><b>Rm release</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHETYPE__RM_RELEASE = eINSTANCE.getArchetype_Rm_release();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHETYPE__NAME = eINSTANCE.getArchetype_Name();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHETYPE__LANGUAGE = eINSTANCE.getArchetype_Language();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHETYPE__DESCRIPTION = eINSTANCE.getArchetype_Description();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHETYPE__DEFINITION = eINSTANCE.getArchetype_Definition();

    /**
     * The meta object literal for the '<em><b>Terminology</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHETYPE__TERMINOLOGY = eINSTANCE.getArchetype_Terminology();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Original Author</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__ORIGINAL_AUTHOR = eINSTANCE.getDescription_OriginalAuthor();

    /**
     * The meta object literal for the '<em><b>Details</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCRIPTION__DETAILS = eINSTANCE.getDescription_Details();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DetailsImpl <em>Details</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.DetailsImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getDetails()
     * @generated
     */
    EClass DETAILS = eINSTANCE.getDetails();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETAILS__NAME = eINSTANCE.getDetails_Name();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETAILS__LANGUAGE = eINSTANCE.getDetails_Language();

    /**
     * The meta object literal for the '<em><b>Use</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETAILS__USE = eINSTANCE.getDetails_Use();

    /**
     * The meta object literal for the '<em><b>Copyright</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETAILS__COPYRIGHT = eINSTANCE.getDetails_Copyright();

    /**
     * The meta object literal for the '<em><b>Other details</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DETAILS__OTHER_DETAILS = eINSTANCE.getDetails_Other_details();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.OtherDetailsImpl <em>Other Details</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.OtherDetailsImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getOtherDetails()
     * @generated
     */
    EClass OTHER_DETAILS = eINSTANCE.getOtherDetails();

    /**
     * The meta object literal for the '<em><b>Lifecycle state</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__LIFECYCLE_STATE = eINSTANCE.getOtherDetails_Lifecycle_state();

    /**
     * The meta object literal for the '<em><b>Custodian namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__CUSTODIAN_NAMESPACE = eINSTANCE.getOtherDetails_Custodian_namespace();

    /**
     * The meta object literal for the '<em><b>Custodian organization</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__CUSTODIAN_ORGANIZATION = eINSTANCE.getOtherDetails_Custodian_organization();

    /**
     * The meta object literal for the '<em><b>License</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__LICENSE = eINSTANCE.getOtherDetails_License();

    /**
     * The meta object literal for the '<em><b>Ip acknowledgement loinc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__IP_ACKNOWLEDGEMENT_LOINC = eINSTANCE.getOtherDetails_Ip_acknowledgement_loinc();

    /**
     * The meta object literal for the '<em><b>Ip acknowledgement snomed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OTHER_DETAILS__IP_ACKNOWLEDGEMENT_SNOMED = eINSTANCE.getOtherDetails_Ip_acknowledgement_snomed();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.OriginalAuthorImpl <em>Original Author</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.OriginalAuthorImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getOriginalAuthor()
     * @generated
     */
    EClass ORIGINAL_AUTHOR = eINSTANCE.getOriginalAuthor();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGINAL_AUTHOR__DATE = eINSTANCE.getOriginalAuthor_Date();

    /**
     * The meta object literal for the '<em><b>Organization</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGINAL_AUTHOR__ORGANIZATION = eINSTANCE.getOriginalAuthor_Organization();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGINAL_AUTHOR__NAME = eINSTANCE.getOriginalAuthor_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGINAL_AUTHOR__EMAIL = eINSTANCE.getOriginalAuthor_Email();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.LangugeImpl <em>Languge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.LangugeImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getLanguge()
     * @generated
     */
    EClass LANGUGE = eINSTANCE.getLanguge();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUGE__NAME = eINSTANCE.getLanguge_Name();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.MatchesImpl <em>Matches</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.MatchesImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getMatches()
     * @generated
     */
    EClass MATCHES = eINSTANCE.getMatches();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATCHES__NAME = eINSTANCE.getMatches_Name();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATCHES__DEFINITION = eINSTANCE.getMatches_Definition();

    /**
     * The meta object literal for the '<em><b>Submatch</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATCHES__SUBMATCH = eINSTANCE.getMatches_Submatch();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATCHES__VALUE = eINSTANCE.getMatches_Value();

    /**
     * The meta object literal for the '<em><b>Value Definition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATCHES__VALUE_DEFINITION = eINSTANCE.getMatches_ValueDefinition();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TerminologyImpl <em>Terminology</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TerminologyImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTerminology()
     * @generated
     */
    EClass TERMINOLOGY = eINSTANCE.getTerminology();

    /**
     * The meta object literal for the '<em><b>Term Definition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINOLOGY__TERM_DEFINITION = eINSTANCE.getTerminology_TermDefinition();

    /**
     * The meta object literal for the '<em><b>Term Binding</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINOLOGY__TERM_BINDING = eINSTANCE.getTerminology_TermBinding();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionsImpl <em>Term Definitions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionsImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermDefinitions()
     * @generated
     */
    EClass TERM_DEFINITIONS = eINSTANCE.getTermDefinitions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_DEFINITIONS__NAME = eINSTANCE.getTermDefinitions_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM_DEFINITIONS__ELEMENTS = eINSTANCE.getTermDefinitions_Elements();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingsImpl <em>Term Bindings</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingsImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermBindings()
     * @generated
     */
    EClass TERM_BINDINGS = eINSTANCE.getTermBindings();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_BINDINGS__NAME = eINSTANCE.getTermBindings_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM_BINDINGS__ELEMENTS = eINSTANCE.getTermBindings_Elements();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionImpl <em>Term Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermDefinitionImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermDefinition()
     * @generated
     */
    EClass TERM_DEFINITION = eINSTANCE.getTermDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_DEFINITION__NAME = eINSTANCE.getTermDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_DEFINITION__TEXT = eINSTANCE.getTermDefinition_Text();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_DEFINITION__DESCRIPTION = eINSTANCE.getTermDefinition_Description();

    /**
     * The meta object literal for the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingImpl <em>Term Binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.TermBindingImpl
     * @see gov.us.fhim.xtext.cimi.cIMIDSL.impl.CIMIDSLPackageImpl#getTermBinding()
     * @generated
     */
    EClass TERM_BINDING = eINSTANCE.getTermBinding();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_BINDING__NAME = eINSTANCE.getTermBinding_Name();

    /**
     * The meta object literal for the '<em><b>Binding</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERM_BINDING__BINDING = eINSTANCE.getTermBinding_Binding();

  }

} //CIMIDSLPackage
