/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getOriginalAuthor <em>Original Author</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getDetails <em>Details</em>}</li>
 * </ul>
 *
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDescription()
 * @model
 * @generated
 */
public interface Description extends EObject
{
  /**
   * Returns the value of the '<em><b>Original Author</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Original Author</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Original Author</em>' containment reference.
   * @see #setOriginalAuthor(OriginalAuthor)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDescription_OriginalAuthor()
   * @model containment="true"
   * @generated
   */
  OriginalAuthor getOriginalAuthor();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getOriginalAuthor <em>Original Author</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Original Author</em>' containment reference.
   * @see #getOriginalAuthor()
   * @generated
   */
  void setOriginalAuthor(OriginalAuthor value);

  /**
   * Returns the value of the '<em><b>Details</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Details</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Details</em>' containment reference.
   * @see #setDetails(Details)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDescription_Details()
   * @model containment="true"
   * @generated
   */
  Details getDetails();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Description#getDetails <em>Details</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Details</em>' containment reference.
   * @see #getDetails()
   * @generated
   */
  void setDetails(Details value);

} // Description
