/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Details</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getName <em>Name</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getLanguage <em>Language</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getUse <em>Use</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getCopyright <em>Copyright</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getOther_details <em>Other details</em>}</li>
 * </ul>
 *
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails()
 * @model
 * @generated
 */
public interface Details extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Language</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Language</em>' attribute.
   * @see #setLanguage(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails_Language()
   * @model
   * @generated
   */
  String getLanguage();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getLanguage <em>Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Language</em>' attribute.
   * @see #getLanguage()
   * @generated
   */
  void setLanguage(String value);

  /**
   * Returns the value of the '<em><b>Use</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use</em>' attribute.
   * @see #setUse(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails_Use()
   * @model
   * @generated
   */
  String getUse();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getUse <em>Use</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use</em>' attribute.
   * @see #getUse()
   * @generated
   */
  void setUse(String value);

  /**
   * Returns the value of the '<em><b>Copyright</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Copyright</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Copyright</em>' attribute.
   * @see #setCopyright(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails_Copyright()
   * @model
   * @generated
   */
  String getCopyright();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getCopyright <em>Copyright</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Copyright</em>' attribute.
   * @see #getCopyright()
   * @generated
   */
  void setCopyright(String value);

  /**
   * Returns the value of the '<em><b>Other details</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Other details</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other details</em>' containment reference.
   * @see #setOther_details(OtherDetails)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getDetails_Other_details()
   * @model containment="true"
   * @generated
   */
  OtherDetails getOther_details();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.Details#getOther_details <em>Other details</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Other details</em>' containment reference.
   * @see #getOther_details()
   * @generated
   */
  void setOther_details(OtherDetails value);

} // Details
