/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getName <em>Name</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getBinding <em>Binding</em>}</li>
 * </ul>
 *
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermBinding()
 * @model
 * @generated
 */
public interface TermBinding extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermBinding_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Binding</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Binding</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding</em>' attribute.
   * @see #setBinding(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermBinding_Binding()
   * @model
   * @generated
   */
  String getBinding();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermBinding#getBinding <em>Binding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding</em>' attribute.
   * @see #getBinding()
   * @generated
   */
  void setBinding(String value);

} // TermBinding
