/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term Definitions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getName <em>Name</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermDefinitions()
 * @model
 * @generated
 */
public interface TermDefinitions extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermDefinitions_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinitions#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link gov.us.fhim.xtext.cimi.cIMIDSL.TermDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage#getTermDefinitions_Elements()
   * @model containment="true"
   * @generated
   */
  EList<TermDefinition> getElements();

} // TermDefinitions
