/*
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCIMIDSLScopeProvider extends DelegatingScopeProvider {
}
