/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.ui;

import gov.us.fhim.xtext.cimi.ui.AbstractCIMIDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CIMIDSLUiModule extends AbstractCIMIDSLUiModule {
  public CIMIDSLUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
