/**
 * generated by Xtext 2.10.0
 */
package org.standardhealh.cimpl.dsl.validation;

import org.standardhealh.cimpl.dsl.validation.AbstractCimplValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CimplValidator extends AbstractCimplValidator {
}
