/*
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.tests

import com.google.inject.Inject
import gov.us.fhim.xtext.cimi.cIMIDSL.ArchetypeModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CIMIDSLInjectorProvider)
class CIMIDSLParsingTest{

	@Inject
	ParseHelper<ArchetypeModel> parseHelper

	@Test 
	def void loadModel() {
//		val result = parseHelper.parse('''
//			Hello Xtext!
//		''')
//		Assert.assertNotNull(result)
	}

}
