/*
 * generated by Xtext 2.12.0
 */
package org.standardhealh.cimpl.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCimplScopeProvider extends DelegatingScopeProvider {
}
