/**
 * generated by Xtext 2.10.0
 */
package org.standardhealh.cimpl.dsl.web;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.standardhealh.cimpl.dsl.web.AbstractCimplWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CimplWebModule extends AbstractCimplWebModule {
}
