/**
 * generated by Xtext 2.10.0
 */
package org.standardhealh.cimpl.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.standardhealh.cimpl.dsl.CimplRuntimeModule;
import org.standardhealh.cimpl.dsl.CimplStandaloneSetup;
import org.standardhealh.cimpl.dsl.web.CimplWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CimplWebSetup extends CimplStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final CimplRuntimeModule runtimeModule = new CimplRuntimeModule();
    final CimplWebModule webModule = new CimplWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public CimplWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
