/**
 * generated by Xtext 2.10.0
 */
package org.standardhealh.cimpl.dsl.web;

import com.google.inject.Injector;
import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.standardhealh.cimpl.dsl.CimplStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CimplWebSetup extends CimplStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nInvalid number of arguments. The constructor CimplWebModule() is not applicable for the arguments (Provider<ExecutorService>)");
  }
  
  public CimplWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
