/**
 * generated by Xtext 2.10.0
 */
package gov.us.fhim.xtext.cimi.cIMIDSL.impl;

import gov.us.fhim.xtext.cimi.cIMIDSL.CIMIDSLPackage;
import gov.us.fhim.xtext.cimi.cIMIDSL.Description;
import gov.us.fhim.xtext.cimi.cIMIDSL.Details;
import gov.us.fhim.xtext.cimi.cIMIDSL.OriginalAuthor;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl#getOriginalAuthor <em>Original Author</em>}</li>
 *   <li>{@link gov.us.fhim.xtext.cimi.cIMIDSL.impl.DescriptionImpl#getDetails <em>Details</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DescriptionImpl extends MinimalEObjectImpl.Container implements Description
{
  /**
   * The cached value of the '{@link #getOriginalAuthor() <em>Original Author</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginalAuthor()
   * @generated
   * @ordered
   */
  protected OriginalAuthor originalAuthor;

  /**
   * The cached value of the '{@link #getDetails() <em>Details</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDetails()
   * @generated
   * @ordered
   */
  protected Details details;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CIMIDSLPackage.Literals.DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OriginalAuthor getOriginalAuthor()
  {
    return originalAuthor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOriginalAuthor(OriginalAuthor newOriginalAuthor, NotificationChain msgs)
  {
    OriginalAuthor oldOriginalAuthor = originalAuthor;
    originalAuthor = newOriginalAuthor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR, oldOriginalAuthor, newOriginalAuthor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOriginalAuthor(OriginalAuthor newOriginalAuthor)
  {
    if (newOriginalAuthor != originalAuthor)
    {
      NotificationChain msgs = null;
      if (originalAuthor != null)
        msgs = ((InternalEObject)originalAuthor).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR, null, msgs);
      if (newOriginalAuthor != null)
        msgs = ((InternalEObject)newOriginalAuthor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR, null, msgs);
      msgs = basicSetOriginalAuthor(newOriginalAuthor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR, newOriginalAuthor, newOriginalAuthor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Details getDetails()
  {
    return details;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDetails(Details newDetails, NotificationChain msgs)
  {
    Details oldDetails = details;
    details = newDetails;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CIMIDSLPackage.DESCRIPTION__DETAILS, oldDetails, newDetails);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDetails(Details newDetails)
  {
    if (newDetails != details)
    {
      NotificationChain msgs = null;
      if (details != null)
        msgs = ((InternalEObject)details).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CIMIDSLPackage.DESCRIPTION__DETAILS, null, msgs);
      if (newDetails != null)
        msgs = ((InternalEObject)newDetails).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CIMIDSLPackage.DESCRIPTION__DETAILS, null, msgs);
      msgs = basicSetDetails(newDetails, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CIMIDSLPackage.DESCRIPTION__DETAILS, newDetails, newDetails));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR:
        return basicSetOriginalAuthor(null, msgs);
      case CIMIDSLPackage.DESCRIPTION__DETAILS:
        return basicSetDetails(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR:
        return getOriginalAuthor();
      case CIMIDSLPackage.DESCRIPTION__DETAILS:
        return getDetails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR:
        setOriginalAuthor((OriginalAuthor)newValue);
        return;
      case CIMIDSLPackage.DESCRIPTION__DETAILS:
        setDetails((Details)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR:
        setOriginalAuthor((OriginalAuthor)null);
        return;
      case CIMIDSLPackage.DESCRIPTION__DETAILS:
        setDetails((Details)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CIMIDSLPackage.DESCRIPTION__ORIGINAL_AUTHOR:
        return originalAuthor != null;
      case CIMIDSLPackage.DESCRIPTION__DETAILS:
        return details != null;
    }
    return super.eIsSet(featureID);
  }

} //DescriptionImpl
