/*
 * generated by Xtext 2.12.0
 */
package org.standardhealh.cimpl.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link CimplWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCimplWebModule extends DefaultWebModule {

}
